'use srtict';

const constants = {
    SUPER_ADMIN: 'super_admin',
    NORMAL_ADMIN: 'normal_admin',
    GENDER_MAN: 'M',
    GENDER_WOMAN: 'F',
    SOURCE_PHONE: 'phone',
    SOURCE_WECHAT: 'wechat',
    SOURCE_QQ: 'qq',
    SOURCE_ADMIN: 'appadmin',
    STATUS_NORMAL: 'normal',
    STATUS_STOP: 'stop',
    USER_TYPE_NORMAL: 'user',
    USER_TYPE_SHOP: 'shop',
    USER_TYPE_APPRAISER: 'appraiser',
    MESSAGE_STATUS_READ: 'read',
    MESSAGE_STATUS_UNREAD: 'unread',
    PLATFORM_IOS: 'iOS',
    PLATFORM_ANDROID: 'Android',
    ORDER_CLOSED: 'closed',
    ORDER_NO: 'nopay',
    ORDER_WAIT_SHIPPING: 'wait-shipping',
    ORDER_WAIT_RECEIVING: 'wait-receiving',
    ORDER_REFUNDING: 'refunding',
    ORDER_COMPLETED: 'completed',
    PERMISSION_ALL: ['admin', 'user', 'message', 'app', 'profit', 'live', 'preview', 'fund', 'applycheck', 'comment', 'auction', 'appraisal', 'recommend'],
    PERMISSION_VIEW: [
        { 'admin': '后台设置' }, { 'user': '用户管理' }, { 'message': '消息管理' },
        { 'app': 'APP管理' }, { 'profit': '分润管理' }, { 'live': '直播管理' },
        { 'preview': '预展区' }, { 'fund': '资金管理' }, { 'applycheck': '申请审核管理' },
        { 'comment': '评论管理' }, { 'auction': '拍卖会管理' }, { 'appraisal': '鉴宝管理' }, {'recommend': '首页推荐'}],
    JISONGJIANBAO: 'jisongjianbao',
    ABOUT_US: 'about-us',
    CONTACT_NUMBER: 'contact-number',
    HOT_WORDS: 'hotwords',
    SENSITIVE_WORDS: 'sensitiveWords',
    LVS_STATUS_IDLE: 'idle',
    LVS_STATUS_LIVING: 'living',
    LVS_STATUS_DISABLED: 'disabled',
    ENCRYPT_PWD: 'usedForEncrypt123456',
    BANNER_TYPE_APP: 'bannerapp',
    BANNER_TYPE_PC: 'bannerpc',
    COMMENT_AUCTION: 'AuctionComment',
    COMMENT_LVS: 'LVSComment',
    COMMENT_POST: 'PostComment',
    APPRAISAL_STATUS_DID: 'did',
    APPRAISAL_STATUS_DID_NOT: 'did-not',
    POST_TYPE_PHOTO: 'photo',
    POST_TYPE_VIDEO: 'video',
    PAYMENT_CHANNEL_WECHAT: 'wechat',
    PAYMENT_CHANNEL_ALIPAY: 'alipay',
    PAYMENT_STATUS_NOPAY: 'nopay',
    PAYMENT_STATUS_SUCCESS: 'success',
    PAYMENT_STATUS_CLOSED: 'closed',
    PAYMENT_STATUS_FINISHED: 'finished',
    PAYMENT_STATUS_FAIL: 'fail',
    PAYMENT_STATUS_REFUNDING: 'refunding',
    PAYMENT_STATUS_REFUND: 'refund',
    TRADE_TYPE_ORDER: 'Order',
    TRADE_TYPE_MARGINMONEY: 'AuctionGoodsMarginMoney',
    TRADE_TYPE_APPRAISAL: 'Appraisal',
    WITHDRAW_STATUS_UNCONFIRMED: 'unconfirmed',
    WITHDRAW_STATUS_CONFIRMED: 'confirmed',
    WITHDRAW_STATUS_COMPLETED: 'completed',
    STATEMENT_CATEGORY_APPRAISAL: 'appraisal',
    STATEMENT_CATEGORY_SELL: 'sell',
    WITHDRAW_ACCOUNT_TYPE_BANKCARD: 'bankcard',
    WITHDRAW_ACCOUNT_TYPE_ALIPAY: 'alipay',
    APPRAISER_TYPE_SELFSUPPORT: 'selfSupport',
    APPRAISER_TYPE_PARTJOB: 'partJob',
    OPEN_SHOP_BG: 'open-shop-bg',
    // 临时的，如果seeders改了，这个就有问题了
    NAME_DES_MAP: {'loginBg': '登录背景图', 'loginBgPC': 'PC登录背景图', 'open-shop-bg': '开店背景图'}

};

module.exports = constants;